### ISSUE TITLE
Install `Kubeadm` in the Vagrant Box

### ISSUE THREAD

**Issue by jdbohrman** [pbacterio/cka_lab#12]
It looks like the box is missing Kubeadm. 
![Screenshot from 2019-04-02 04-34-44](https://user-images.githubusercontent.com/27848025/55388166-c8477d00-5500-11e9-9d42-c95a54ae808b.png)
![Screenshot from 2019-04-02 04-34-16](https://user-images.githubusercontent.com/27848025/55388167-c8477d00-5500-11e9-95cb-889107aab916.png)

**Comment by pbacterio** [comment]
I've found a dependencia conflict installing kubelet and kubeadm.
```
Processing Dependency: kubernetes-cni = 0.6.0 for package: kubelet-1.13.2-0.x86_64
Processing Dependency: kubernetes-cni >= 0.6.0 for package: kubeadm-1.13.2-0.x86_64
```
