### ISSUE TITLE
kubectl is not able to reach the api server  one the cluster lunched

### ISSUE THREAD

**Issue by samyzm** [pbacterio/cka_lab#7]
The connection to the server localhost:8080 was refused - did you specify the right host or port?
--

during the vagrant up i got  this logs:

+ join_cmd='failed to load admin kubeconfig [open /root/.kube/config: no such file or directory]'
--

**Comment by pbacterio** [comment]
Found this:
    `master: 	[ERROR SystemVerification]: unsupported docker version: 18.09.1`

Kubernetes 1.11 version do not support latest docker version.

Changed docker setup to use a fixed valid version: #8
